### ISSUE TITLE
Stacktrace on startup

### ISSUE THREAD

**Issue by hayco** [gmandnepr/IdeaConcordionSupport#27]
java.lang.ExceptionInInitializerError
	at org.concordion.plugin.idea.ConcordionPsiUtils.<clinit>(ConcordionPsiUtils.java:31)
	at org.concordion.plugin.idea.ConcordionNavigationService.correspondingTestFixture(ConcordionNavigationService.java:42)
	at org.concordion.plugin.idea.patterns.ConcordionElementPattern$1.accepts(ConcordionElementPattern.java:47)
	at org.concordion.plugin.idea.patterns.ConcordionElementPattern$1.accepts(ConcordionElementPattern.java:37)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:69)
	at org.concordion.plugin.idea.marker.AbstractLineMarkerProvider.getLineMarkerInfo(AbstractLineMarkerProvider.java:42)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:157)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:90)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.intellij.psi.PsiPrimitiveType.<init>(PsiPrimitiveType.java:33)
	at com.intellij.psi.PsiType.<clinit>(PsiType.java:17)
	... 28 more
	
	
	
INDUCED:

Following exceptions happened soon after this one, most probably they are induced.

2021-02-22T13:19:58.640
java.lang.NoClassDefFoundError: Could not initialize class org.concordion.plugin.idea.ConcordionPsiUtils
	at org.concordion.plugin.idea.ConcordionNavigationService.correspondingTestFixture(ConcordionNavigationService.java:42)
	at org.concordion.plugin.idea.patterns.ConcordionElementPattern$1.accepts(ConcordionElementPattern.java:47)
	at org.concordion.plugin.idea.patterns.ConcordionElementPattern$1.accepts(ConcordionElementPattern.java:37)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:69)
	at org.concordion.plugin.idea.marker.AbstractLineMarkerProvider.getLineMarkerInfo(AbstractLineMarkerProvider.java:42)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:157)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:90)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by hayco** [comment]
<img width="908" alt="Screenshot 2021-02-22 at 13 22 13" src="https://user-images.githubusercontent.com/2081891/108707906-fda04e00-7510-11eb-87ec-e2df4f98799b.png">

**Comment by nigelcharman** [comment]
Possible duplicate of #25. Which version of IDEA are you using? We saw this in 2020.3 beta but was resolved in 2020.3.

**Comment by hayco** [comment]
I don't remember. I had to disable the plugin as this was blocking. I just re-enabled it in 2021.1 Beta and it seems to have gone away.
